// Define the Member type
export type Member = {
  id: number
  name: string
  imageUrl: string
  pledgeClass: string
  linkedinUrl: string
}

// Sort pledge classes chronologically
export const sortPledgeClasses = (a: string, b: string): number => {
  const [aSeason, aYear] = a.split(" ")
  const [bSeason, bYear] = b.split(" ")

  if (aYear !== bYear) {
    return Number.parseInt(aYear) - Number.parseInt(bYear)
  }

  const seasonOrder = { Spring: 0, Summer: 1, Fall: 2, Winter: 3 }
  return seasonOrder[aSeason as keyof typeof seasonOrder] - seasonOrder[bSeason as keyof typeof seasonOrder]
}


// Member data
export const members: Member[] = [
  {
    id: 1,
    name: "Lily Anderson",
    imageUrl: "/spring25_headshots/LilyA.webp",
    pledgeClass: "Fall 2022",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 4,
    name: "Liam Gaiden",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Fall 2022",
    linkedinUrl: "https://www.linkedin.com/in/liam-gaiden",
  },
  {
    id: 5,
    name: "Mariana Alibali",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Fall 2022",
    linkedinUrl: "https://www.linkedin.com/in/mariana-alibali",
  },
  {
    id: 7,
    name: "Grace Bowen",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Fall 2022",
    linkedinUrl: "https://www.linkedin.com/in/grace-bowen-1047a6247/",
  },
  {
    id: 13,
    name: "Ben Levy",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Spring 2023",
    linkedinUrl: "https://www.linkedin.com/in/ben-levy-125781206",
  },
  {
    id: 14,
    name: "Zack Wagner",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Spring 2023",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 15,
    name: "Arshiya Chugh",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Spring 2023",
    linkedinUrl: "https://www.linkedin.com/in/arshiya-chugh-b67114261",
  },
  {
    id: 16,
    name: "Mihir Patil",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Fall 2023",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 17,
    name: "Drew Hay",
    imageUrl: "/spring25_headshots/DrewH.webp",
    pledgeClass: "Fall 2023",
    linkedinUrl: "https://www.linkedin.com/in/drewzhay",
  },
  {
    id: 22,
    name: "Navya Jain",
    imageUrl: "/spring25_headshots/NavyaJ.webp",
    pledgeClass: "Fall 2023",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 23,
    name: "Theo Fowler",
    imageUrl: "/spring25_headshots/TheoF.webp",
    pledgeClass: "Fall 2023",
    linkedinUrl:
      "https://www.linkedin.com/in/theo-fowler-82037432a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  },
  {
    id: 26,
    name: "Zahabiyah Boty",
    imageUrl: "/spring25_headshots/ZahabiyahB.webp",
    pledgeClass: "Fall 2023",
    linkedinUrl: "https://www.linkedin.com/in/zahabiyah-boty/",
  },
  {
    id: 27,
    name: "Jackie Behring",
    imageUrl: "/spring25_headshots/JackieBehring.webp",
    pledgeClass: "Fall 2023",
    linkedinUrl: "https://www.linkedin.com/in/jacqueline-behring-645853310/",
  },
  {
    id: 29,
    name: "Guillemette Schroepfer",
    imageUrl: "/spring25_headshots/Guillemette.JPG",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/guillemette-schroepfer-685818263/",
  },
  {
    id: 30,
    name: "Ben Bossman",
    imageUrl: "/spring25_headshots/BenBossman.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 31,
    name: "Sophia Prondzinski",
    imageUrl: "/spring25_headshots/SophiaP.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/sophia-prondzinski",
  },
  {
    id: 32,
    name: "Sydney Magee",
    imageUrl: "/spring25_headshots/SydneyM.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/sydney-magee-a9a0232b4",
  },
  {
    id: 35,
    name: "Annie Zhao",
    imageUrl: "/spring25_headshots/AnnieZ.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/-annie-zhao/",
  },
  {
    id: 38,
    name: "Kate Briesemeister",
    imageUrl: "/spring25_headshots/KateB.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/katebriesemeister/",
  },
  {
    id: 39,
    name: "Shubh Arora",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 41,
    name: "Henry Czupryna",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/henry-czupryna-2b3044250/",
  },
  {
    id: 42,
    name: "Elizabeth Risgaard",
    imageUrl: "/spring25_headshots/ElizabethR.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/elizabeth-risgaard-960b642b2",
  },
  {
    id: 45,
    name: "Kayla Radtke",
    imageUrl: "/spring25_headshots/KaylaR.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/kayla-radtke",
  },
  {
    id: 47,
    name: "Jaden Tan",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/jaden-tann",
  },
  {
    id: 48,
    name: "Walter Van Dyke",
    imageUrl: "/spring25_headshots/WalterVD.webp",
    pledgeClass: "Spring 2024",
    linkedinUrl: "https://www.linkedin.com/in/walter-van-dyke",
  },
  {
    id: 49,
    name: "Garret Donohue",
    imageUrl: "/spring25_headshots/GarretD.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/garret-donohue",
  },
  {
    id: 50,
    name: "Abby Burger",
    imageUrl: "/spring25_headshots/AbbyB.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/abby-burger-07708232a",
  },
  {
    id: 51,
    name: "Violet Urdahl",
    imageUrl: "/spring25_headshots/VioletU.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/violet-urdahl",
  },
  {
    id: 52,
    name: "Hadeel Manimaran",
    imageUrl: "/spring25_headshots/HadeelM.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/hadeelmanimaran/",
  },
  {
    id: 53,
    name: "Damek Mangum",
    imageUrl: "/spring25_headshots/DamekM.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/damek-mangum-b93186223",
  },
  {
    id: 54,
    name: "Ben Walther",
    imageUrl: "/spring25_headshots/BenW.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/ben-walther-304305307/",
  },
  {
    id: 55,
    name: "Siri Stolen",
    imageUrl: "/spring25_headshots/SiriStolen.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 56,
    name: "Aadya Ganjigunta",
    imageUrl: "/spring25_headshots/AadyaG.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/aadyaganjigunta",
  },
  {
    id: 57,
    name: "Christian Sacia-Garcia",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/christian-sacia-garcia",
  },
  {
    id: 58,
    name: "Chandini Krejcarek",
    imageUrl: "/spring25_headshots/ChandiniK.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 59,
    name: "Neil Deore",
    imageUrl: "/spring25_headshots/NeilD.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/neildeore",
  },
  {
    id: 60,
    name: "Emma Stroshane",
    imageUrl: "/spring25_headshots/EmmaS.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/EmmaStroshane",
  },
  {
    id: 61,
    name: "Julia Geng",
    imageUrl: "/spring25_headshots/JuliaG.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/julia-geng-543b672a8/",
  },
  {
    id: 62,
    name: "Alex Haas",
    imageUrl: "/spring25_headshots/AlexH.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/alex-haas-aa3141331/",
  },
  {
    id: 63,
    name: "Ellie Fecko",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 64,
    name: "Joseph McIlwain",
    imageUrl: "/spring25_headshots/JosephM.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/joseph-mcilwain-a79382331",
  },
  {
    id: 65,
    name: "Alan Chen",
    imageUrl: "/spring25_headshots/AlanC.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "http://linkedin.com/in/alan-chen-52122a2a2",
  },
  {
    id: 66,
    name: "Noahdiah Lisowski",
    imageUrl: "/spring25_headshots/NoahdiahL.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/NoahdiahLisowski",
  },
  {
    id: 67,
    name: "Sam Snyder",
    imageUrl: "/spring25_headshots/SamS.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/sam-snyder-318942327",
  },
  {
    id: 68,
    name: "Evan Loe",
    imageUrl: "/spring25_headshots/EvanL.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/evan-loe-a940b0266/",
  },
  {
    id: 69,
    name: "Carson Donze",
    imageUrl: "/spring25_headshots/CarsonDonze.webp",
    pledgeClass: "Fall 2024",
    linkedinUrl: "https://www.linkedin.com/in/carson-donze-52b48632a/",
  },
  {
    id: 70,
    name: "Annika Chudy",
    imageUrl: "/spring25_headshots/AnnikaC.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/annika-chudy/",
  },
  {
    id: 71,
    name: "Arik Sargeant",
    imageUrl: "/spring25_headshots/ArikSargeant.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/arik-sargeant-8286a0325/",
  },
  {
    id: 72,
    name: "Ben Belew",
    imageUrl: "/spring25_headshots/BenBelew.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/ben-belew-7b6b51327/",
  },
  {
    id: 73,
    name: "Colin Lazzara",
    imageUrl: "/spring25_headshots/ColinL.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/colin-lazzara-724900353/",
  },
  {
    id: 74,
    name: "Darcy Moore",
    imageUrl: "/spring25_headshots/DarcyM.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/darcy-moore/",
  },
  {
    id: 75,
    name: "Ella Barsness",
    imageUrl: "/spring25_headshots/EllaB.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/ella-barsness-54760422b/",
  },
  {
    id: 76,
    name: "Everett Kaeli",
    imageUrl: "/spring25_headshots/EverettK.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/everett-kaeli-71a10a304/",
  },
  {
    id: 77,
    name: "Fiona Dragan",
    imageUrl: "/spring25_headshots/FionaD.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/fiona-dragan/",
  },
  {
    id: 78,
    name: "Gage Helgeson",
    imageUrl: "/spring25_headshots/GageH.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/gage-helgeson-57269234b/",
  },
  {
    id: 79,
    name: "Hunter Cooke",
    imageUrl: "/spring25_headshots/HunterC.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/hunter-cooke-a5926a29a/",
  },
  {
    id: 80,
    name: "Jamie Lennon",
    imageUrl: "/spring25_headshots/JamieL.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/jamie-lennon-795216306/",
  },
  {
    id: 81,
    name: "Jessica Rolain",
    imageUrl: "/spring25_headshots/JessicaR.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/jessica-r-5b477a235/",
  },
  {
    id: 82,
    name: "Julia Hyman",
    imageUrl: "/spring25_headshots/JuliaH.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/julia-hyman-279a96343/",
  },
  {
    id: 83,
    name: "Katie Duffy",
    imageUrl: "/spring25_headshots/KatieD.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/katie-m-duffy/",
  },
  {
    id: 84,
    name: "Katie Jenson",
    imageUrl: "/spring25_headshots/KatieJenson.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/katie-jenson-23bb22335/",
  },
  {
    id: 85,
    name: "Lauren Anderson",
    imageUrl: "/spring25_headshots/LaurenA.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/lauren-anderson-15b0a1349/",
  },
  {
    id: 86,
    name: "Leonardo Losch",
    imageUrl: "/spring25_headshots/LeonardoL.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/leonardo-losch-3a64462a3/",
  },
  {
    id: 87,
    name: "Luke Van Overmeiren",
    imageUrl: "/spring25_headshots/LukeVO.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/luke-van-overmeiren-bba3b834b/",
  },
  {
    id: 88,
    name: "Lydia Lim",
    imageUrl: "/spring25_headshots/LydiaL.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/lydialim06/",
  },
  {
    id: 89,
    name: "Philip Gu",
    imageUrl: "/spring25_headshots/PhilipG.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/philip-gu-3892b3337/",
  },
  {
    id: 90,
    name: "Sabrina Garcia",
    imageUrl: "/spring25_headshots/SabrinaG.webp",
    pledgeClass: "Spring 2025",
    linkedinUrl: "https://www.linkedin.com/in/sabrina-garcia-657942304/",
  },
  {
    id: 91,
    name: "Andrew Wolf",
    imageUrl: "/fall25pc/Andrew_Wolf.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/wolfandrew00/",
  },
  {
    id: 92,
    name: "Annika Weir",
    imageUrl: "/fall25pc/Annika_Weir.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 93,
    name: "Avery Gunn",
    imageUrl: "/fall25pc/Avery_Gunn.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 94,
    name: "Bella Belgiorno",
    imageUrl: "/fall25pc/Bella_Belgiorno.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/isabella-belgiorno/",
  },
  {
    id: 95,
    name: "Brady Mayer",
    imageUrl: "/fall25pc/Brady_Mayer.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "http://linkedin.com/in/brady-mayer",
  },
  {
    id: 96,
    name: "Bridget Jensen",
    imageUrl: "/fall25pc/Bridget_Jensen.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/bridget-jensen-886113319",
  },
  {
    id: 97,
    name: "Christian McIlheran",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 98,
    name: "Claire Casson",
    imageUrl: "/fall25pc/Claire_Casson.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/clairehcasson",
  },
  {
    id: 99,
    name: "Clinton Woodmansee",
    imageUrl: "/fall25pc/Clinton_Woodmansee.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 100,
    name: "Dara Golden",
    imageUrl: "/fall25pc/Dara_Golden.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 101,
    name: "Dhanvi Ramji",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 102,
    name: "Dylan Libel",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 103,
    name: "Emma Cavazos",
    imageUrl: "/fall25pc/Emma_Cavazos.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/emma-cavazos",
  },
  {
    id: 104,
    name: "Finley Moss",
    imageUrl: "/fall25pc/Finley_Moss.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 105,
    name: "Kaitlin Gish",
    imageUrl: "/fall25pc/Kaitlin_Gish.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/kaitlingish/",
  },
  {
    id: 106,
    name: "Kellie Mueller",
    imageUrl: "/fall25pc/Kellie_Mueller.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 107,
    name: "Lauren Hain",
    imageUrl: "/fall25pc/Lauren_Hain.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 108,
    name: "Lily Tapparo",
    imageUrl: "/fall25pc/Lily_Tapparo.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 109,
    name: "Nevin Sunny",
    imageUrl: "/fall25pc/Nevin_Sunny.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 110,
    name: "Sarah Bransky",
    imageUrl: "/spring25_headshots/TT.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/thetatauxi/",
  },
  {
    id: 111,
    name: "Sullivan Neumeier",
    imageUrl: "/fall25pc/Sullivan_Neumeier.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/sullivan-neumeier",
  },
  {
    id: 112,
    name: "Will Quinn",
    imageUrl: "/fall25pc/Will_Quinn.webp",
    pledgeClass: "Fall 2025",
    linkedinUrl: "https://www.linkedin.com/in/WillQuinn1",
  },
]
